#pragma once
inline const char *LangIT = R"====(
{
  "Age":"Età",
  "AgeGlyc":"Età della glicemia",
  "Compte":"Account",
  "Display":"Display",
  "Infos":"Informazioni",
  "Lang":"Lingua",
  "F_Hor":"Fuso orario",
  "Apropos":"Informazioni",
  "Restart":"Riavvio",
  "InitWifi":"Inizializzazione WiFi",
  "Version":"Versione: ",
  "Nom_WiFi": "Rete WiFi: ",
  "MotDePasse":"Password: ",
  "RechercheWiFi":"Ricerca WiFi:",
  "ConnectedWiFi":"Connesso tramite WiFi, indirizzo IP: ",
  "ou":" o ",
  "EchecWiFi":"Connessione WiFi fallita",
  "SelectWifi":"Seleziona WiFi",
  "ScanStart":"Scansione reti in corso",
  "ScanTermine":"Scansione completata",
  "PasReseau":"Nessuna rete WiFi trovata",
  "reseauxTrouves":" reti trovate",
  "WaitGluco":"In attesa della glicemia",
  "LoginFailed":" Nessuna connessione a Libreview, codice HTTP: ",
  "LastGlyco":" Ultima glicemia nota: ",
  "le":" il ",
  "GlucoFailed":" Nessun dato glicemico da Libreview, codice HTTP: ",
  "GraphFailed":" Nessun grafico da Libreview, codice HTTP: ",
  "NoRecentGluco":"Nessuna glicemia recente",
  "LinkUpIndefini":"Account LibreLinkUp non definito",
  "Serveur80":"Server web attivo sulla porta 80",
  "Update":"Aggiornamento",
  "UpdateComplete":"Aggiornamento completato",
  "ParaConfig":"Impostazioni di configurazione",
  "Historique":"Storico",
  "Luminosite":"Luminosità schermo notturno",
  "Rotation":"Rotazione schermo",
  "Refuse":"Rifiuta",
  "Accept":"Accetta",
  "OKData":"Accesso ai dati autorizzato",
  "Clavier":"Tastiera",
  "PassWiFi":"Password della rete WiFi: ",
  "EmailLinkUp":"Email account LibreLinkUp",
  "PasseLinkUp":"Password account LibreLinkUp",
  "Modifier":"Modifica",
  "Tester":"Test",
  "Password":"Password",
  "Undefined":"Non definito",
  "ServerZone":"Zona server",
  "ConnectOK":"Connessione riuscita!",
  "UserUnknown":"Utente sconosciuto sul server",
  "ServerNoAccess":"Server non raggiungibile",
  "VersionSoft":"Versione software: ",
  "Auteur":"Autore",
  "AdrIP":"Indirizzo IP: ",
  "NoWiFi":"WiFi non connesso a: ",
  "GlucoOn":"Gluco-Monitor attivo da: ",
  "Cancel":"Annulla",
  "ListWiFi":"Elenco reti WiFi",
  "byF1ATB":"di F1ATB",
  "Glucose":"Glicemia",
  "dataLibreview":"Dati Libreview",
  "Arbo":"Clicca su {} per aprire o chiudere l'albero",
  "DisplayArbo":"Visualizzazione ad albero dei messaggi JSON Libreview",
  "LogLibreview":"Accesso a Libreview",
  "ConnectLibreview":"Connessione a Libreview",
  "GraphLibreview":"Grafico Libreview",
  "UpdateOTA":"Aggiornamento software tramite OTA",
  "VersionNow":"La tua versione attuale di Gluco-Monitor: ",
  "VersionDispo":"Versione/i disponibile/i: ",
  "Telecharge":"1 - Scarica sul tuo computer la versione binaria desiderata del Gluco-Monitor",
  "ClickBin":"cliccando su di essa",
  "SelectFile":"2 - Clicca su 'Scegli file' e seleziona questo binario sul tuo computer",
  "SendBin":"3 - Clicca su ",
  "SenBinBut":"Invia binario",
  "AutoOnMonitor":"Autorizza l'accesso sul monitor"
}
)====";